# http
POST http://localhost:5000/api/wilders
content-type: application/json

{
  "name":"Mikasa",
  "city":"Lyon",
  "profilePicture": "https://i.pinimg.com/originals/97/61/dd/9761dda5106bd111c8983870e4d699c5.jpg",
  "skills":[
    {"title":"Eren", "votes":20},
    {"title":"Équipement Tridimensionnel", "votes":20}
    ]
}

###
GET http://localhost:5000/api/wilders

###
GET http://localhost:5000/api/wilders/622764c29f4d2bf08e5c5f0b


###
PATCH http://localhost:5000/api/wilders/622764c29f4d2bf08e5c5f0b
content-type: application/json

{

  "city":"Lyon"
 
}

###
DELETE http://localhost:5000/api/wilders/622868835312a978eb8199fc
Content-Type: application/json

###
GET http://localhost:5000/api/doc/
